### ISSUE TITLE
Branch / commit

### ISSUE THREAD

**Issue by ComLock** [enonic/app-gitpull#3]
Typically people put configs for all environments in a single repository with a branch per environment.

Does this app support checking out a branch or a commit?

If not can you please add support for it.

**Comment by ComLock** [comment]
In fact since some configuration is different per cluster node, there needs to be one branch per cluster node.

**Comment by rymsha** [comment]
git pull of a specific commit makes little sense.

#8 asks for branch pull, which is done.
