### ISSUE TITLE
dir = ${xp.home}/config does not work

### ISSUE THREAD

**Issue by ComLock** [enonic/app-gitpull#4]
Trying:
```
name.dir = ${xp.home}/config
```

Will give this error:
```
ERROR c.e.app.gitpull.GitRepoPullerImpl - Error cloning git repository [name] org.eclipse.jgit.api.errors.JGitInternalException: Destination path "config" already exists and is not an empty directory
```

Which means setting up this app to handle all config could be difficult.

I'm gonna try this approach:

1. Make a git repo with all config files including a com.enonic.app.gitpull.cfg file.
2. Stop enonic
3. Delete ${xp.home}/config
4. Manually git clone the repo to ${xp.home}/config
5. Start Enonic
6. Change some file on the remote
7. Trigger the gitpull endpoint

**Comment by ComLock** [comment]
I've gotten to point 5 and got this. I'll try to get around it.
```
2017-11-15 13:06:02,868 ERROR c.e.app.gitpull.GitRepoPullerImpl - Error pulling git repository [mistral]
org.eclipse.jgit.api.errors.TransportException: http://username@url/enonic-xp-config.git: Authentication is required but no CredentialsProvider has been registered
```

**Comment by sigdestad** [comment]
Christian, I don't think gitpull should not be used to control the entire $XP_HOME/config as there are files such as system.properties that should not be updated like this (require restart of entire system).

**Comment by rymsha** [comment]
This app is not for XP config
