### ISSUE TITLE
Support for branches

### ISSUE THREAD

**Issue by dholmen** [enonic/app-gitpull#8]
Configurable support for branches would be really useful, and the last piece of the puzzle in order to enable us to use this app in our setup.

For example:
```
prod.url = https://some/git/url
prod.user = username
prod.password = password
prod.dir = ${xp.home}/config
**prod.branch = master**
```

**Comment by sigdestad** [comment]
Seems like an interesting approach..

**Comment by rymsha** [comment]
duplicate of #3
